spring:
  application:
    name: trade
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 2000
    jedis:
      pool:
        min-idle: 50
        max-idle: 500
        max-active: 2000
        max-wait: 1000

  data:
    mongodb:
      uri: mongodb://localhost:27017/trade



server:
  port: 3001


# HttpClient配置
http:
  client:
    connection:
      maxTotal: 200
      defaultMaxPerRoute: 20
    request:
      connectionRequestTimeout: 500
      connectTimeout: 1000
      socketTimeout: 600000

# 服务地址
message:
  url: http://localhost:3000
  service:
    daily: /pro_bar/<asset>/<ts_code>/<start_date>/<end_date>
    trade_cal: /trade_cal/<exchange>/<start_date>/<end_date>
    stock_basic: /stock_basic
    index_basic: /index_basic/<market>

##日志文件配置
logging:
  config: classpath:logback.xml

## 指数 - 市场说明(market)
trade:
  index_basic_markets:
    MSCI: "MSCI指数"
    CSI: "中证指数"
    SSE: "上交所指数"
    SZSE: "深交所指数"
    CICC: "中金指数"
    SW: "申万指数"
    OTH: "其他指数"
  used_index_basic_tsCodes:
    "000001.SH": "上证指数"
    "399001.SZ": "深证成指"
    "000016.SH": "上证50"
    "000300.SH": "沪深300指数"
    "000905.SH": "中证500指数"
